In [2]:
import numpy as np
import pandas as pds
import matplotlib.pyplot as plt
from matplotlib import pylab
import seaborn as sns
sns.set_style("whitegrid")

In [31]:
noShow = pds.read_csv('../datasets/Inasistencias/KaggleV2-May-2016 V03.csv', sep = ";")
print(noShow.head())

   Unnamed: 0          PatientId  AppointmentID Gender  \
0           0   29872499824296.0        5642903      F
1           1  558997776694438.0        5642503      M
2           2    4262962299951.0        5642549      F
3           3     867951213174.0        5642828      F
4           4    8841186448183.0        5642494      F

  AppointmentRegistration AppointmentData  Age      Neighbourhood  \
0        29/04/2016 18:38      29/04/2016   62    JARDIM DA PENHA
1        29/04/2016 16:08      29/04/2016   56    JARDIM DA PENHA
2        29/04/2016 16:19      29/04/2016   62      MATA DA PRAIA
3        29/04/2016 17:29      29/04/2016    8  PONTAL DE CAMBURI
4        29/04/2016 16:07      29/04/2016   56    JARDIM DA PENHA

   Scholarship  Hypertension  Diabetes  Alchoholism  Handicap  SMS_received  \
0            0             1         0            0         0             0
1            0             0         0            0         0             0
2            0             0         0            0         0             0
3            0             0         0            0         0             0
4            0             1         1            0         0             0

  No-show  AwaitingTime DayOfTheWeek
0      No             1      viernes
1      No             1      viernes
2      No             1      viernes
3      No             1      viernes
4      No             1      viernes

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [37]:
noShow.head()

,Unnamed: 0,PatientId,AppointmentID,Gender,AppointmentRegistration,AppointmentData,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alchoholism,Handicap,SMS_received,No-show,AwaitingTime,DayOfTheWeek
0,0,29872499824296.0,5642903,F,29/04/2016 18:38,29/04/2016,62,JARDIM DA PENHA,0,1,0,0,0,0,No,1,viernes
1,1,558997776694438.0,5642503,M,29/04/2016 16:08,29/04/2016,56,JARDIM DA PENHA,0,0,0,0,0,0,No,1,viernes
2,2,4262962299951.0,5642549,F,29/04/2016 16:19,29/04/2016,62,MATA DA PRAIA,0,0,0,0,0,0,No,1,viernes
3,3,867951213174.0,5642828,F,29/04/2016 17:29,29/04/2016,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,1,viernes
4,4,8841186448183.0,5642494,F,29/04/2016 16:07,29/04/2016,56,JARDIM DA PENHA,0,1,1,0,0,0,No,1,viernes

In [45]:
noShow.dtypes

Unnamed: 0                  int64
PatientId                  object
AppointmentID               int64
Gender                     object
AppointmentRegistration    object
AppointmentData            object
Age                         int64
Neighbourhood              object
Scholarship                 int64
Hypertension                int64
Diabetes                    int64
Alchoholism                 int64
Handicap                    int64
SMS_received                int64
No-show                    object
AwaitingTime                int64
DayOfTheWeek               object
dtype: object

In [33]:
noShow.rename(columns = {'Alcoholism': 'Alchoholism',
                         'Hipertension': 'Hypertension',
                         'ScheduledDay': 'AppointmentRegistration',
                         'ApointmentData': 'AppointmentData',
                         'Handcap': 'Handicap'}, inplace = True)

print(noShow.columns)

Index(['Unnamed: 0', 'PatientId', 'AppointmentID', 'Gender',
       'AppointmentRegistration', 'AppointmentData', 'Age', 'Neighbourhood',
       'Scholarship', 'Hypertension', 'Diabetes', 'Alchoholism', 'Handicap',
       'SMS_received', 'No-show', 'AwaitingTime', 'DayOfTheWeek'],
      dtype='object')

In [34]:
noShow.head()

,Unnamed: 0,PatientId,AppointmentID,Gender,AppointmentRegistration,AppointmentData,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alchoholism,Handicap,SMS_received,No-show,AwaitingTime,DayOfTheWeek
0,0,29872499824296.0,5642903,F,29/04/2016 18:38,29/04/2016,62,JARDIM DA PENHA,0,1,0,0,0,0,No,1,viernes
1,1,558997776694438.0,5642503,M,29/04/2016 16:08,29/04/2016,56,JARDIM DA PENHA,0,0,0,0,0,0,No,1,viernes
2,2,4262962299951.0,5642549,F,29/04/2016 16:19,29/04/2016,62,MATA DA PRAIA,0,0,0,0,0,0,No,1,viernes
3,3,867951213174.0,5642828,F,29/04/2016 17:29,29/04/2016,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,1,viernes
4,4,8841186448183.0,5642494,F,29/04/2016 16:07,29/04/2016,56,JARDIM DA PENHA,0,1,1,0,0,0,No,1,viernes

In [35]:
#perdidas    Tuberculosis
#por elaborar:  AwaitingTime    .  DayOfTheWeek   :  LISTAS

In [48]:
print('Age:',sorted(noShow.Age.unique()))
print('Gender:',noShow.Gender.unique())
print('DayOfTheWeek:',noShow.DayOfTheWeek.unique())
print('Status:',noShow.Status.unique())
print('Diabetes:',noShow.Diabetes.unique())
print('Alchoholism:',noShow.Alchoholism.unique())
print('Hypertension:',noShow.Hypertension.unique())
print('Handicap:',noShow.Handicap.unique())
print('Smokes:',noShow.Smokes.unique())
print('Scholarship:',noShow.Scholarship.unique())
print('Tuberculosis:',noShow.Tuberculosis.unique())
print('Sms_Reminder:',noShow.Sms_Reminder.unique())
print('AwaitingTime:',sorted(noShow.AwaitingTime.unique()))
print('HourOfTheDay:', sorted(noShow.HourOfTheDay.unique()))

Age: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 102, 115]
Gender: ['F' 'M']
DayOfTheWeek: ['viernes' 'martes' 'lunes' 'mi�rcoles' 'jueves' 's�bado']

AttributeError: 'DataFrame' object has no attribute 'Status'

In [ ]:
mainpath = "/Users/JUNTAS/Documents/GitHub/python-ml-course/datasets/Inasistencias/KaggleV2-May-2016 V01.csv"
noShow.to_csv(mainpath)